### ISSUE TITLE
Planning/Handover of ribbon webcomponents

### ISSUE THREAD

**Issue by lpalbou** [geneontology/wc-ribbon#29]
* Knowledge transfer to @tmushayahama 

* Update READ me to reflect [gdoc](https://docs.google.com/document/d/1CAXTRvmx5zIR3YpBl5834cl_-V1333dqwAuXJxVx2KU/edit) and [ppt](https://docs.google.com/presentation/d/16eIch-uRFu39mynL-9UXuCrhisrzpb8g/edit#slide=id.p5)

* Reminder: NPM releases are done with the GO organization (@geneontology)
```
npm run build
npm version patch (for instance)
npm publish
```

* Quick note on how to test Alliance integration:
main GH: https://github.com/alliance-genome/agr_ui
```
npm install
export API_URL=https://build.alliancegenome.org
npm start
```

* Create a Jira account for @tmushayahama

**Comment by cmungall** [comment]
Also: consider renaming this repo, e.g go-core-webcomponents, to reflect that there are different WCs here independent of ribbon, e.g. AC

**Comment by cmungall** [comment]
Update from call today

@tmushayahama has code up and running locally

**Comment by cmungall** [comment]
Clarification from call:

to release to alliance

 1. release to NPM
 2. make a PR on agr_ui to get new version

**Comment by lpalbou** [comment]
@lpalbou organize 2h on monday / tuesday

**Comment by kltm** [comment]
Talking to @tmushayahama @dustine32 @sierra-moxon : feels are good .
